# Generated by Django 6.0.1 on 2026-02-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('purpose', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=100)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
