# Generated by Django 6.0.1 on 2026-02-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(choices=[('Business Meeting', 'Business Meeting'), ('Interview', 'Interview'), ('Delivery', 'Delivery'), ('Maintenance', 'Maintenance'), ('Personal Visit', 'Personal Visit'), ('Other', 'Other')], max_length=200),
        ),
    ]
